project:
  type: website

execute:
  freeze: auto
  echo: false # Set default to not show the R code
  

# Website structure
website:
  title: "Female Travel and Mobility during the Dutch Revolt"
  site-url: https://jessesadler.github.io/quarto-web-example/
  navbar:
    right: # have links to pages begin from right ride
      - href: index.qmd # file to be used for homepage
        text: Home # text to be used for link to enable title of page to be different
      - text: The women
        menu: # Create drop-down menu with the following pages
         - href: anna-df.qmd
         - href: hester-df.qmd
         - href: zeghers.qmd
         - href: anna-vdm.qmd
         - href: sarah-vdm.qmd
      - context.qmd # Add another page
      - href: movements.qmd
        text: Visualizing female travel
      - about.qmd # About page
      - icon: github # Link to the GitHub page
        href: https://github.com/jessesadler/quarto-web-example

# Options applied to all pages
format:
  html:
    theme:
      - cosmo
      - styles.scss
    toc: true

# Settings for citations and bibliography
bibliography: references.bib
csl: https://www.zotero.org/styles/chicago-fullnote-bibliography
suppress-bibliography: true
# Place all citations in bibliography even if not in a footnote.
nocite: |
  @*



