project:
  type: website

execute:
  freeze: auto

website:
  title: "Female Travel and Mobility during the Dutch Revolt"
  navbar:
    right: # have links to pages begin from right ride
      - href: index.qmd # file to be used for homepage
        text: Home # text to be used for link to enable title of page to be different
      - text: The women
        menu:
         - href: anna-df.qmd
         - href: hester-df.qmd
         - href: zeghers.qmd
         - href: anna-vdm.qmd
         - href: sarah-vdm.qmd
      - context.qmd # Add another page
      - href: movements.qmd
        text: Visualizing female travel
      - about.qmd

format:
  html:
    theme:
      - cosmo
    css: styles.scss
    toc: true
bibliography: references.bib
csl: https://www.zotero.org/styles/chicago-fullnote-bibliography
suppress-bibliography: true
nocite: |
  @*



