project:
  type: website

website:
  title: "Female Travel and Mobility during the Dutch Revolt"
  navbar:
    right: # have links to pages begin from right ride
      - href: index.qmd # file to be used for homepage
        text: Home # text to be used for link to enable title of page to be different
      - context.qmd # Add another page
      - about.qmd

format:
  html:
    theme:
      - cosmo
    css: styles.scss
    toc: true
bibliography: references.bib
csl: https://www.zotero.org/styles/chicago-fullnote-bibliography
suppress-bibliography: true
nocite: |
  @*



