---
title: "Anna van der Meulen"
---

- Born: 1544-1546
- Married Severijn de Corput in September 1573 in Frankfurt
- Married Francois Pierens between 1576 and 1582
- Death: Unknown

As the oldest child of Jan and Elizabeth, Anna played an important role in maintaining unity within her sibling group. Anna married twice, and both of her husbands entered into trade companies with Elizabeth. In September 1573, at the age of about twenty-eight, Anna married Severijn de Corput, a merchant from Breda who had gained citizenship in Antwerp in 1572, when she would have been about twenty-years old. The couple moved to Antwerp and had a son, Hansken, in 1574. Severijn signed an agreement to enter into a company with his mother-in-law to begin in 1575, but he died before the commencement of the company. By 1582, Anna had remarried to François Pierens. The marriage likely took place in or before 1581 when François began the "Oude Compagnie" with Elizabeth. Before his marriage to Anna, François had worked in a company with Antoine and Jan Lempereur that traded in parallel with Elizabeth's activities. With his marriage, François ended the company with the Lempereurs and invested his capital with his mother-in-law.

After Elizabeth returned to Antwerp in 1582, François directed the trading activities in Germany from Cologne, where he and Anna lived until 1588. In 1586 François and the the Van der Meulens created another company. The Nieuwe Compagnie, (1585–1591) consisted of François for a one-third part, Anna's brothers Andries and Daniel for a combined one-third part, and Antoine Lempereur, Francois's former partner and now brother-in-law through Antoine's marriage to Sara van der Meulen, for the final one-third. The company possessed a total capital of £12,000, which it directed towards the fairs of Frankfurt and Strasbourg just as the "Oude Compagnie" had done. Over the course of the company, the trading activities of the brothers-in-law expanded to include Hamburg, Cologne, Emden, Amsterdam, Middelburg, and London. Over the years, the company began to concentrate on the trade of textiles from the Low Countries and England to the fairs in exchange for Italian goods. François was expected to do much of the work for the company and was to be provided with an additional 1/12 part in the profits.

Anna and François had at least three children, but little is known about them. Anna's child from her first marriage, Hansken, was mostly raised in the household of Andries. After a short stay in Andries's house in Bremen, they moved to the port city of Stade in 1588. In 1592, they returned to Bremen to live alongside Anna's siblings. They appear to have lived in Bremen until at least 1618. Anna and François both developed close relations to Anna's siblings. François appears as a pious husband and brother-in-law in his letters to his affines. Anna's letters to her siblings often spoke of the various ailments which seemed to constantly inflict her. She worried greatly when François left the house for business and had trouble sleeping at night.