---
title: "Anna della Faille"
---

- Born: 1543
- Marriage to Robert van Eeckeren: June 1562
	- Robert was 35 at the time of the marriage
- Death: 16 October 1622

Jan della Faille Oude’s oldest daughter married her father’s factor, Robert van Eeckeren in June 1562. Robert's stepmother was Anna de Hane, his wife’s maternal grandmother. The couple lived in Seville until 1573, when they returned to Antwerp and Robert was appointed warden of currency. Anna and Robert retreated to Haarlem during the siege of Antwerp, but they quickly returned as soon as Antwerp fell. Robert’s loyalty was demonstrated when he was nominated as almoner along with his brother-in-law, Marten, in 1585. Robert’s religious persuasion is shown by a request that he made along with Marten to the magistrates of Antwerp to keep the children of Maria and Louis Malapert in Antwerp so that they could be raised Catholic. Faithful to king and Church, Robert and Anna also stayed loyal to Marten in the disputes between the siblings over the estate of Jan de Oude.