---
title: "Hester della Faille"
---

- Born: 1558/59
- Marriage to Daniel van der Meulen on 25 December 1584
- Death: 28 May 1643

In his testament, Jan de Oude indicated that his two unmarried daughters must marry with full approval of the three executors. Hester put this article to the test in her decision to marry Daniel van der Meulen against the wishes of Marten. Having converted to Calvinism by this time, Hester married Daniel in the Walloon church in Haarlem on 24 December 1584. All of her children were baptized and raised in the Calvinist manner. After the fall of Antwerp, Hester and Daniel lived in Bremen for a period of six years. In September 1591, Daniel, Hester, and their four children moved to the university city of Leiden. In the divisions of her father's estate, Hester mostly sided with Jacques. She developed a close relationship with Jacques’s wife Josina Hamels, and they two corresponded with each other in parallel to the correspondence of their husbands. However, after Daniel agreed to have received full payment of Hester’s inheritance with Marten in 1594, Hester wrote to her brother, telling him that she continued to be his "faithful sister."

Fifteen of Hester's letters to her husband have been preserved. While Daniel was away from Leiden on various trips, Hester was tasked with heading the household and, along with Daniel’s bookkeeper, dealing with any business. Her letters to her husband often contained information about their children, especially any malady they may have contracted. After her husband’s death in 1600, Hester continued to work and invest in the company that Daniel had made with his brother Andries and Andries’s brother-in-law Nicolas Malapert. Hester possessed and used her own trade mark even before Daniel’s death. Hester returned to Antwerp in 1610 after the beginning of the Twelve-Year Truce to visit Marten and deal with the landed property that she owned in Antwerp. She returned to Antwerp in 1618. Hester continued to live in Leiden until 1634, and she died on 28 May 1643 in The Hague. She was buried in Leiden next to her husband in the Pieterskerk.