---
title: "Sarah van der Meulen"
---

- Born: 1552/53
- Married Antoine Lempereur in February 1586
- Death: April 1618

Sent to live in Cologne at the age of about ten, Sara only returned to Antwerp with her mother in 1582. Once in Antwerp, she and her younger sister must have helped their mother with the household duties and also likely assisted with the accounting and other mercantile business where possible. At the age of thirty-two, she received a suitor in the person of Antoine Lempereur, the former partner of her brother-in-law, François. Antoine wrote to Sara throughout 1584 and 1585 while Antwerp was under siege. The delay in Antoine’s planned arrival in Antwerp and the breaks in his correspondence made Sara question her feelings for Antoine, but the fall of Antwerp and Sara’s extrication to Bremen opened the way for the engagement to finally take place. The two signed a marriage agreement on 13 November 1585. On the same day, Antoine signed the agreement with his soon to be brothers-in-law to form the Nieuwe Compagnie, (1585–1591) Antoine was tasked with the bookkeeping for the firm, and like Francois Pierens, the terms of the agreement dictated that he could not trade outside the bounds of the company. Sara and Antoine married in February 1586.

Sara and Antoine lived in Cologne when they first married, near François and Anna. Many of the letters that Andries wrote to Sara in 1587 were addressed to both Sara and Anna. The letters show that Sara was a competent bookkeeper in her own regard. Like her older sister, her husband’s frequent trips to the fairs in Frankfurt and Strasbourg or to Bremen to meet with Andries and Daniel meant that she was often left in the house alone to take care of business matters. Sara and Antoine moved to Bremen in 1589 and then to Utrecht in 1598. Sara and Antoine seem to have encouraged their five boys to pursue academic interests. In 1607, the family moved to Leiden, a year after their oldest son matriculated in the law faculty. Their four younger sons matriculated into the faculty of arts in the following years. Finally, in 1615, Antoine and Sara moved to Amsterdam, where both died.