---
title: "Elizabeth Zeghers"
---

- Born: About 1520
- Death: 17 June 1587

Elizabeth Zeghers was born in Lier to Aerts Zeghers and Anna van Eynde. Both of her parents had died by the time that she married Jan. In her marriage contract, her guardians were Willem van Eynde, her uncle on the mother's side and her brother-in-law, Jan de Hoest de Oude. Elizabeth, like all merchant wives, must have been essential help to her husband in running her mercantile business. At the death of her husband in 1563, Elizabeth took over the family capital and traded on her own. As her sons grew older, they too joined in the family trade, working under the auspices of their mother. Under Elizabeth’s lead, the family capital continued to expand, so that by the time of her death, the Van der Meulens counted among the mercantile elite of Antwerp.

With the troubles from the beginnings of the Dutch Revolt stirring around them, Elizabeth sent her three daughters and youngest son to Cologne in 1572. She joined her children two years later, as her two oldest sons took greater responsibility in the family’s trading activities. From Cologne, Elizabeth directed the activities of her sons between the metropolis of Antwerp and the biannual fairs at Frankfurt and Strasbourg, acting as middlemen in the exchange of goods between northwest Europe and the Italian peninsula. After an abortive attempt at creating a company with her son-in-law, Severijn van de Corput in 1575, Elizabeth formed a company with her son-in-law François Pierens in 1581. Elizabeth constituted the senior partner in the so-called “Oude Compagnie,” bringing two-thirds of the capital with François contributing the other one-third. The company continued to trade along the same lines, though they also expanded their trade to Nuremberg.

With the failure of the peace talks in Cologne in 1579 and the declaration of the Calvinist Republic in Antwerp, Elizabeth returned to Antwerp in 1582. It is unclear when the Van der Meulen family converted to Calvinism, and conversion does seem to have been a united family affair for the Van der Meulens, but if the conversion occurred before 1579, the Van der Meulens must have been clandestine Calvinists. By 1581, the family had clearly adopted Calvinism and stood firmly on the side of Revolt. Elizabeth remained in Antwerp until she was forced into exile after the fall of Antwerp to Farnese on 17 August 1585. Elizabeth retreated to Bremen, which possessed a small enclave of Calvinist exiles, along with her sons Andries and Daniel and their families. There, under the watchful eyes of her two sons, Elizabeth died on 17 June 1587.