{
  "hash": "796127114dafcea90b94354bde412f96",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"The historical context\"\n---\n\nThe advance of the armies of [Alexander Farnese](https://en.wikipedia.org/wiki/Alexander_Farnese,_Duke_of_Parma) into Flanders from 1580, culminating in the capture of Antwerp in August of 1585 precipitated a period of mass mobility as both rebels and loyalists traveled to avoid the dangers of war and those associated with the Revolt were eventually forced into exile.[@Arnade_2008; @Soen_2012] \n\n\n::: {.cell}\n\n:::\n\n\n\n::: {.cell}\n\n:::\n\n\nThe major towns captured by Farnese are noted in the below table, which uses the [gt package](https://gt.rstudio.com/index.html).\n\n\n::: {#tbl-reconquest .cell}\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"yqnnqwhwlm\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#yqnnqwhwlm table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#yqnnqwhwlm thead, #yqnnqwhwlm tbody, #yqnnqwhwlm tfoot, #yqnnqwhwlm tr, #yqnnqwhwlm td, #yqnnqwhwlm th {\n  border-style: none;\n}\n\n#yqnnqwhwlm p {\n  margin: 0;\n  padding: 0;\n}\n\n#yqnnqwhwlm .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#yqnnqwhwlm .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#yqnnqwhwlm .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#yqnnqwhwlm .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#yqnnqwhwlm .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#yqnnqwhwlm .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#yqnnqwhwlm .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#yqnnqwhwlm .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#yqnnqwhwlm .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#yqnnqwhwlm .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#yqnnqwhwlm .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#yqnnqwhwlm .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#yqnnqwhwlm .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#yqnnqwhwlm .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#yqnnqwhwlm .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#yqnnqwhwlm .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#yqnnqwhwlm .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#yqnnqwhwlm .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#yqnnqwhwlm .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#yqnnqwhwlm .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#yqnnqwhwlm .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#yqnnqwhwlm .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#yqnnqwhwlm .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#yqnnqwhwlm .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#yqnnqwhwlm .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#yqnnqwhwlm .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#yqnnqwhwlm .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#yqnnqwhwlm .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#yqnnqwhwlm .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#yqnnqwhwlm .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#yqnnqwhwlm .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#yqnnqwhwlm .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#yqnnqwhwlm .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#yqnnqwhwlm .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#yqnnqwhwlm .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#yqnnqwhwlm .gt_left {\n  text-align: left;\n}\n\n#yqnnqwhwlm .gt_center {\n  text-align: center;\n}\n\n#yqnnqwhwlm .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#yqnnqwhwlm .gt_font_normal {\n  font-weight: normal;\n}\n\n#yqnnqwhwlm .gt_font_bold {\n  font-weight: bold;\n}\n\n#yqnnqwhwlm .gt_font_italic {\n  font-style: italic;\n}\n\n#yqnnqwhwlm .gt_super {\n  font-size: 65%;\n}\n\n#yqnnqwhwlm .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#yqnnqwhwlm .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#yqnnqwhwlm .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#yqnnqwhwlm .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#yqnnqwhwlm .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#yqnnqwhwlm .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#yqnnqwhwlm .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#yqnnqwhwlm .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#yqnnqwhwlm div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_heading\">\n      <td colspan=\"2\" class=\"gt_heading gt_title gt_font_normal gt_bottom_border\" style>The reconquest of Alexander Farnese</td>\n    </tr>\n    \n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"location\">City</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"date\">Year</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"location\" class=\"gt_row gt_left\">Kortrijk</td>\n<td headers=\"date\" class=\"gt_row gt_right\">1580</td></tr>\n    <tr><td headers=\"location\" class=\"gt_row gt_left\">Breda</td>\n<td headers=\"date\" class=\"gt_row gt_right\">1580</td></tr>\n    <tr><td headers=\"location\" class=\"gt_row gt_left\">Oudenaarde</td>\n<td headers=\"date\" class=\"gt_row gt_right\">1582</td></tr>\n    <tr><td headers=\"location\" class=\"gt_row gt_left\">Lier</td>\n<td headers=\"date\" class=\"gt_row gt_right\">1582</td></tr>\n    <tr><td headers=\"location\" class=\"gt_row gt_left\">Hulst</td>\n<td headers=\"date\" class=\"gt_row gt_right\">1583</td></tr>\n    <tr><td headers=\"location\" class=\"gt_row gt_left\">Zutphen</td>\n<td headers=\"date\" class=\"gt_row gt_right\">1583</td></tr>\n    <tr><td headers=\"location\" class=\"gt_row gt_left\">Bruges</td>\n<td headers=\"date\" class=\"gt_row gt_right\">1584</td></tr>\n    <tr><td headers=\"location\" class=\"gt_row gt_left\">Ghent</td>\n<td headers=\"date\" class=\"gt_row gt_right\">1584</td></tr>\n    <tr><td headers=\"location\" class=\"gt_row gt_left\">Brussels</td>\n<td headers=\"date\" class=\"gt_row gt_right\">1585</td></tr>\n    <tr><td headers=\"location\" class=\"gt_row gt_left\">Mechelen</td>\n<td headers=\"date\" class=\"gt_row gt_right\">1585</td></tr>\n    <tr><td headers=\"location\" class=\"gt_row gt_left\">Antwerp</td>\n<td headers=\"date\" class=\"gt_row gt_right\">1585</td></tr>\n    <tr><td headers=\"location\" class=\"gt_row gt_left\">Nijmegen</td>\n<td headers=\"date\" class=\"gt_row gt_right\">1585</td></tr>\n  </tbody>\n  \n</table>\n</div>\n```\n\n:::\n:::\n\n\nThe below map shows the major events in the reconquest of Farnese in the first half of the 1580s. It includes the plotting code used to make the map.\n\n:::{.column-page}\n\n\n::: {.cell layout-align=\"left\"}\n\n```{.r .cell-code}\nggplot(data = reconquest_sf) +\n  geom_spatraster(data = lc_raster, alpha = 0.6,\n                  show.legend = FALSE) +\n  scale_fill_whitebox_c(palette = \"atlas\", direction = 1) +\n  geom_sf(data = oceans, color = NA, fill = \"lightblue\") +\n  geom_sf(data = lakes, color = NA, fill = \"lightblue\") +\n  geom_sf(data = rivers, color = \"lightblue\", size = 0.4) +\n  geom_sf(aes(color = factor(date)), size = 4) +\n  geom_text_repel(aes(x = long, y = lat, label = location),\n                  size = 3) +\n  scale_color_brewer(palette = \"RdPu\") + \n  coord_sf(xlim = c(3400000, 3900000),\n           ylim = c(2600000, 3000000),\n           expand = FALSE, datum = NA) +\n  labs(title = \"The reconquest of Farnese, 1580–1585\",\n       color = \"Year of conquest\") +\n  theme_void() +\n  theme(plot.title = element_text(size = 18),\n        legend.position = \"top\",\n        legend.direction = \"horizontal\")\n```\n\n::: {.cell-output-display}\n![The reconquest of Farnese, 1580–1585.](context_files/figure-html/fig-reconquest-1.png){#fig-reconquest fig-align='left' fig-alt='A map of the Low Countries showing the reconquest of Farnese\nwith the towns captured between 1580 and 1585.' width=960}\n:::\n:::\n\n\n:::\n",
    "supporting": [
      "context_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}